[workspace]
members = [
    "apps/cli",
    "crates/engine",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release.package."*"]
opt-level = "z"
