[tools]
pnpm = "latest"
rust = "latest"
node = "latest"
claude-code = "latest"
bun = "latest"

[tasks.pre-commit]
run = [
  "cargo fmt",
  "cargo clippy --fix --allow-dirty",
]

[tasks.test]
run = [
  "cargo test -- --test-threads=24",
]
