[package]
name = "beetle_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = "0.24"
walkdir = "2.3"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
