/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexesRouteImport } from './routes/indexes'
import { Route as IndexRouteImport } from './routes/index'

const IndexesRoute = IndexesRouteImport.update({
  id: '/indexes',
  path: '/indexes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indexes': typeof IndexesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indexes': typeof IndexesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indexes': typeof IndexesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/indexes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/indexes'
  id: '__root__' | '/' | '/indexes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexesRoute: typeof IndexesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/indexes': {
      id: '/indexes'
      path: '/indexes'
      fullPath: '/indexes'
      preLoaderRoute: typeof IndexesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexesRoute: IndexesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
